### ISSUE TITLE
Flamm disp infil calcs don't use dispersion time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [grgrgrknght/facet3d-issues#196]
```
current flamm disp sip calcs an outdoor conc limit based on ach and 10 min. 
change to a more detailed eval where the actual disp duration is included 
similar to toxic infil calcs.
```

Original issue reported on code.google.com by `grgrgrkn...@gmail.com` on 5 Nov 2014 at 5:27

**Comment by grgrgrknght** [comment]
Commit facet3d@e5e5597452415b29a9db8c3ad0628ed361f5fcf0 implemented this change. Upon building ACH set, a 1D curve is created (outdoor conc vs. duration) to get the specified (typ. 1/2 LFL) indoor concentration. The analysis code uses the dispersion maxtime to get the outdoor concentration to test against at each buildings location. This change assumes the concentration at the building remains fixed for the dispersions duration. It will be conservative for dispersions that have decreasing concentrations like when the release stops and a *shrinking* pool is left.
