### ISSUE TITLE
Support Click-drag Implementation for Highlight Command Options

### ISSUE THREAD

**Issue by GoogleCodeExporter** [grgrgrknght/facet3d-issues#198]
```
The title pretty much says it all. It would be very helpful for the Rectangle 
and possible the Box options.
```

Original issue reported on code.google.com by `wein3...@gmail.com` on 26 Mar 2015 at 7:23

**Comment by grgrgrknght** [comment]
rectangle already has this and since box is 3D I cannot define a box in one click drag.
