### ISSUE TITLE
Detailed Fire Gridding Errors

### ISSUE THREAD

**Issue by grgrgrknght** [grgrgrknght/facet3d-issues#205]
FACET really needs to provide some sort of coordinate reference if it fails to create a mesh, when running an unstructured grid. This would allow the user to have an idea of which geometry element or mesh control is causing the error.

**Comment by grgrgrknght** [comment]
Mike, do you have an setup that fails so I can determine where to catch the error?

**Comment by wein3967** [comment]
I know which project it is. I'll just need to mess with the grid regions to
generate the error.

Michael Weinberg
Project Manager
ABS Consulting
140 Heimer Road, Suite 300
San Antonio, TX  78232-5075
210-495-5195 (office)
MWeinberg@absconsulting.com <mweinberg@absconsulting.com>
http://www.absconsulting.com/

**Comment by wein3967** [comment]
Greg,

Managed to generate the error ;)

See Northern Tier file in Z:\Data Transfers\GRK\FACET_Crash

Thanks.

Michael Weinberg
Project Manager
ABS Consulting
140 Heimer Road, Suite 300
San Antonio, TX  78232-5075
210-495-5195 (office)
MWeinberg@absconsulting.com <mweinberg@absconsulting.com>
http://www.absconsulting.com/

**Comment by grgrgrknght** [comment]
now allows orphan verticies.
