### ISSUE TITLE
Commandline Prompt for Zoom Level via Scale Size

### ISSUE THREAD

**Issue by wein3967** [grgrgrknght/facet3d-issues#233]
It would be helpful to be able to specify the zoom level by using the command prompt to specify the size, in feet, of the displayed scale bar. For example, if I want to make an older image where the scale bar was 570 ft long, I could type ZoomScale (zm) and 570, and FACET would determine the camera zoom necessary to make the scale bar display 570 ft.

**Comment by grgrgrknght** [comment]
Using a middle mouse button press and moving the mouse vertically allows you to change zoom in a continuous manner. It is pretty easy to then get the scale bar to the desired dimension.

**Comment by wein3967** [comment]
Awesome. I did not know that. Thanks.
