### ISSUE TITLE
Independent Mesh Controls (IMC) Rendering Options

### ISSUE THREAD

**Issue by wein3967** [grgrgrknght/facet3d-issues#234]
Several things that essentially request that IMC act and are largely treated like Regions render-wise (e.g. line-weight, surface, line, surface/line). It would be helpful to be able to mass change color of IMCs.

A possible issue here is that IMCs can be paths and not necessarily "regions." However, I imagine the vast majority of their use is as regions. A separate section could be added for paths.

**Comment by grgrgrknght** [comment]
done
