### ISSUE TITLE
FACET Beta 17.4.7 BDL Report Order and Delimiter Error

### ISSUE THREAD

**Issue by wein3967** [grgrgrknght/facet3d-issues#244]
Running a BDL report in the FACET beta (17.4.7) is resulting in incorrectly formed and non-delimited PivotTable data. Example:

> BDL Pivot Table
> Building,Scenario,BDL
> 0101 - Office1
> 02a01 - Office6
> 02b01 - Office6

This data is being written as ScenarioBldNameBDL instead of as expected from the header.

**Comment by wein3967** [comment]
Turns out this is an issue for several reports that generate PivotTable data this way (e.g. Building Screening)

**Comment by grgrgrknght** [comment]
fixed and beta updated
