### ISSUE TITLE
Combining buildings in building damage report

### ISSUE THREAD

**Issue by vsantalov** [grgrgrknght/facet3d-issues#246]
A building that consists of several buildings (building a, building b, etc.) may have one of the building's PI curves disabled because we do not care about damage to that building part but we still would like to show it in figures. When the BDL report combines the buildings the damage is reported correctly from the enabled PI curves but the message still appears:
_(warning: building has 0 enabled PIs)_
In the screen shot below I disabled the PI curves for the vestibule part of building 10:
![image](https://user-images.githubusercontent.com/12448681/29194808-ec489222-7df0-11e7-9718-b228cb7457dd.png)

**Comment by grgrgrknght** [comment]
changed warning to "one or more building(s) has ..."
